include hyde.conf
include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family CaskaydiaMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0

# Keybindings
map F11 toggle_fullscreen
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
map shift+enter send_text all \n
map ctrl+shift+a send_text all \x01\x0b

# Move windows around
map ctrl+shift+left move_window left
map ctrl+shift+right move_window right
map ctrl+shift+up move_window up
map ctrl+shift+down move_window down

# Resize windows
map ctrl+alt+left resize_window narrower
map ctrl+alt+right resize_window wider
map ctrl+alt+up resize_window taller
map ctrl+alt+down resize_window shorter

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no

# Shell
shell /usr/bin/zsh

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
